### ISSUE TITLE
app_tdd: BAUDOT_FIGURE_SHIFT undefined on certain distros?

### ISSUE THREAD

**Issue by InterLinked1** [dgorski/app_tdd#17]
Seems like possible spandsp compatibility issues again. From a hosted GitHub Actions runner:

```
   [CC] app_tdd.c -> app_tdd.o
app_tdd.c: In function 'tdd_v18_decode_baudot':
app_tdd.c:373:10: error: 'BAUDOT_FIGURE_SHIFT' undeclared (first use in this function)
  373 |     case BAUDOT_FIGURE_SHIFT:
      |          ^~~~~~~~~~~~~~~~~~~
app_tdd.c:373:10: note: each undeclared identifier is reported only once for each function it appears in
app_tdd.c:376:10: error: 'BAUDOT_LETTER_SHIFT' undeclared (first use in this function)
  376 |     case BAUDOT_LETTER_SHIFT:
      |          ^~~~~~~~~~~~~~~~~~~
   [CC] app_test.c -> app_test.o
make[1]: *** [/usr/src/asterisk-20.2.1/Makefile.rules:165: app_tdd.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:396: apps] Error 2
Error: Process completed with exit code 2.
```

**Comment by InterLinked1** [comment]
@dgorski Any thoughts on this at all? Just did some more tests to see if I could re-enable this in builds, and it still does this on both Debian 10 and Debian 11. I'm mainly curious if you're seeing this at all or if it's something particular to certain ways of building.

Interestingly, in the spandsp repo this seems to be only in .c files, not header files. Not sure if this is a recent change or just GitHub's sloppy search, I haven't looked deeper. Are these defined in the header files on your system still?

**Comment by dgorski** [comment]
Strange,

Can you tell which spandsp version this is happening with?

There is actually a define just above this spot in the code do deal with the newer spandsp that the freeswitch guys released (and some distros picked up) because it's no longer exposed by that version of the library (which is dumb).  However, it should be exposed in the earlier spandsp releases - at least it used to be.

Need to determine the cases where this happens - I could just always define it (rather than conditionally), but that would likely cause warnings related to redefined symbols...

So I guess I would need to understand the scenario (probably spandsp version) where this is happening, so I can figure out an appropriate fix for it.

- Darrin

**Comment by InterLinked1** [comment]
Here's the Debian 10 system:

```
#define SPANDSP_RELEASE_DATE            20110122
#define SPANDSP_RELEASE_TIME            075024
#define SPANDSP_RELEASE_DATETIME_STRING "20110122 075024"
```

Debian 11 appears the same
```
#define SPANDSP_RELEASE_DATE            20110122
#define SPANDSP_RELEASE_TIME            075024
#define SPANDSP_RELEASE_DATETIME_STRING "20110122 075024"
```

**Comment by dgorski** [comment]
I am not clear how this symbol was ever visible, which is odd becuase this builds on my ubuntu 20 system with libspandsp-dev of 0.0.6 (which is effectively the same as your debian versions).  However, I cannot find any include file that exposes these defines, so I don't know how it is building.  That said, I'll simply `if !defined()` them which will define them if they are needed and not if they are already there.  This way it avoids warnings but also isn't broken.

**Comment by dgorski** [comment]
Builds against 18.16.0 on my ubuntu 20 system.  Let me know if this fixes your debian 10/11 builds and I'll close.

**Comment by InterLinked1** [comment]
Builds fine now on Debian 10, I'd assume the same of everything else, thanks!

**Comment by dgorski** [comment]
Thanks, I'll close it.
