### ISSUE TITLE
Invalid baudot characters

### ISSUE THREAD

**Issue by nicchap** [dgorski/app_tdd#22]
Should we be filtering non character returns (octet = 0xff) as well, around line 485 ? 
It causes an error in line 677 or 682 (statis_message_blob) 

ie: `else if (octet == 0x0d || octet == 0xff) { span_log(&s->logging, SPAN_LOG_FLOW, "filtering CR (0x0d, 0xff)"); }`

**Comment by dgorski** [comment]
Interesting - the V18 modem is placed into 5-bit mode, so a char should never be > 31.  I didn't think it was possible to get a char back from the v11 modem in 5-bit mode that didn't match the table in decode_baudot (which is exactly 32 in size, or 2^5).  However, I suppose that since it is a possible case, it should be handled.  I'll add a line to filter that as well.  You mention it causes an error - so you've seen this happen?  It seems... impossible.

**Comment by dgorski** [comment]
fixed in #dec1d4a

**Comment by dgorski** [comment]
FYI - this is absolutely possible and even very likely - when a SHIFT is received, the decoder has to return something, so FF is used to indicate that a char was NOT received.  This should have been filtered from the very beginning, thanks for catching it.

**Comment by nicchap** [comment]
Thanks for looking into this. To answer your question: Yes, I saw this happen quite frequently. Maintaining code = not always easy.
